language: python3

python:
  - "3.4.3"

install:
  - "pip3 -r install -U requirements.txt"

script:
  - py.test

notifications:
  slack:
    rooms:
      - smartstudy:vss6xLp9Qw4uPjdsvqlvquMK#build
  email: false
